### ISSUE TITLE
Are you looking for volunteers?

### ISSUE THREAD

**Issue by joker314** [uuffda/uuffda#2]
Not asking for any reason whatsoever \*whistles\*?

**Comment by bjskistad** [comment]
Yeah, "we" are looking for some more people to "employ". Of course, by "employ"ed we mean volunteer for an open source company.

**Comment by bjskistad** [comment]
@joker314 Would you like to join?

**Comment by joker314** [comment]
Then I will gladly "work" for "you", so long as b doing so I am not violating laws where I live (as in, child labour laws), though I doubt they apply for volunteers. I got confused when you changed the name btw :stuck_out_tongue: If I'm not mistaken this used to be called chikadi?

**Comment by bjskistad** [comment]
Awesome! The reason it is now Uuffda, is because I rebranded for a shorter name.
